---
- name: Network Getting Started First Playbook
  connection: network_cli
  hosts: localhost
  remote_user: root
  become_method: sudo
  become_user: root
  vars:
    http_port: 2222
    max_clients: 200
  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
    - name: Install Curl and Which
      yum:
        name: 
          - curl
          - which
        state: latest
    - name: Install Confluent Platform public key
      sudo: yes
      rpm_key:
        key=https://packages.confluent.io/rpm/5.0/archive.key
        state=present
    - name: Navigate to /etc/yum.repos.d/ and create confluent.repo
      copy:
        dest: "/etc/yum.repos.d/confluent.repo"
        content: |
          [Confluent.dist]
          name=Confluent repository (dist)
          baseurl=https://packages.confluent.io/rpm/5.0/7
          gpgcheck=1
          gpgkey=https://packages.confluent.io/rpm/5.0/archive.key
          enabled=1
          
          [Confluent]
          name=Confluent repository
          baseurl=https://packages.confluent.io/rpm/5.0
          gpgcheck=1
          gpgkey=https://packages.confluent.io/rpm/5.0/archive.key
          enabled=1
    - name: Clear YUM caches
      shell: yum clean all
    - name:  install confluent-platform-oss-2.11
      yum:
        name: confluent-platform-oss-2.11
        state: latest

